CREATE TABLE doctors
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name         VARCHAR(255),
    email        VARCHAR(255),
    crm          VARCHAR(255),
    specialty    VARCHAR(255),
    street       VARCHAR(255),
    neighborhood VARCHAR(255),
    zipcode      VARCHAR(255),
    number       VARCHAR(255),
    additional   VARCHAR(255),
    city         VARCHAR(255),
    state        VARCHAR(255),
    CONSTRAINT pk_doctors PRIMARY KEY (id)
);