CREATE TABLE patient
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name         VARCHAR(255),
    email        VARCHAR(255),
    phone_number VARCHAR(255),
    cpf          VARCHAR(255),
    is_active    BOOLEAN                                 NOT NULL,
    street       VARCHAR(255),
    neighborhood VARCHAR(255),
    zipcode      VARCHAR(255),
    number       VARCHAR(255),
    additional   VARCHAR(255),
    city         VARCHAR(255),
    state        VARCHAR(255),
    CONSTRAINT pk_patient PRIMARY KEY (id)
);